### ISSUE TITLE
Adding licence

### ISSUE THREAD

**Issue by JanPerret** [dewshr/NCBI-GenBank-file-parser#2]
Hi,

Could you add a licence to this code ? I think it is certainly an oversight.

Thank you in advance,
Jan

**Comment by dewshr** [comment]
done.

**Comment by JanPerret** [comment]
Thanks a lot !

If you're interested I wrote a program with a similar purpose but without using Biopython : https://github.com/JanPerret/NCBI-GenBank-metadata-extractor

Your code served me as a starting point, so I thank you a lot for sharing !

Jan

**Comment by dewshr** [comment]
happy to know it was helpful.
